import type { SubscriptionTemplate } from './types.ts'

/**
 * Вручную проверенные/переоценённые шаблоны подписок.
 *
 * Базовый принцип (из ТЗ): лучше оставить сумму пустой, чем подставить
 * неверную. По умолчанию любая неуверенность → `amount: null`,
 * `amount_type: 'unknown'`, `price_confidence: 'unknown'`,
 * `should_autofill_amount: false`. Автоподстановка суммы разрешена
 * только когда цена фиксирована, проверена и применима к региону
 * пользователя (RU).
 */
export const CURATED_TEMPLATES: SubscriptionTemplate[] = [
  // ──────────────────────────────────────────────────────────────
  // RU стриминг / экосистемы
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:yandex-plus',
    provider: 'Яндекс',
    name: 'Яндекс Плюс',
    display_name: 'Яндекс Плюс',
    aliases: ['yandex plus', 'яндекс плюс', 'плюс мульти', 'яндекс плюс мульти'],
    icon: 'subscriptions',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    is_bundle: true,
    included_services: ['Кинопоиск', 'Яндекс Музыка'],
    plans: [
      {
        id: 'curated:yandex-plus:base',
        name: 'Плюс Мульти',
        billing_cycle: 'monthly',
        amount: 449,
        currency: 'RUB',
        amount_type: 'fixed',
        price_confidence: 'high',
        region: ['RU'],
        payment_sources: ['website'],
        notes: 'Базовая цена на сайте; есть промо-периоды и семейные/студенческие тарифы с другой ценой.',
      },
    ],
    management_url: 'https://plus.yandex.ru',
    cancellation_url: 'https://plus.yandex.ru/my',
    pricing_url: 'https://plus.yandex.ru',
    detection_keywords: ['яндекс плюс', 'yandex plus', 'yandex.plus'],
    should_autofill_amount: true,
    should_show_in_suggestions: true,
    user_warning: 'Возможны промо-цена для новых пользователей и отдельные семейные/студенческие тарифы — проверьте сумму списания.',
    notes: 'Цена подтверждена на официальном сайте plus.yandex.ru на момент проверки.',
  },
  {
    id: 'curated:kinopoisk',
    provider: 'Яндекс',
    name: 'Кинопоиск',
    display_name: 'Кинопоиск',
    aliases: ['kinopoisk', 'кинопоиск', 'кинопоиск hd'],
    icon: 'movie',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:kinopoisk:bundled',
        name: 'Кинопоиск (в составе Яндекс Плюс)',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
        notes: 'Кинопоиск не продаётся отдельной подпиской — доступ идёт в составе Яндекс Плюс.',
      },
    ],
    management_url: 'https://plus.yandex.ru',
    detection_keywords: ['кинопоиск', 'kinopoisk'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Кинопоиск не продаётся отдельно — обычно это часть подписки Яндекс Плюс. Проверьте, не дублируете ли вы её.',
    notes: 'Не нашли отдельного тарифа на сайте — только в составе Плюса.',
  },
  {
    id: 'curated:vk-music',
    provider: 'VK',
    name: 'VK Музыка',
    display_name: 'VK Музыка',
    aliases: ['вк музыка', 'vk music', 'boom', 'бум'],
    icon: 'music_note',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:vk-music:base',
        name: 'VK Музыка',
        billing_cycle: 'monthly',
        amount: 199,
        currency: 'RUB',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['RU'],
        notes: 'Цена встречается у агрегаторов; не подтверждена напрямую на официальной странице на момент проверки.',
      },
    ],
    management_url: 'https://vk.com/music',
    detection_keywords: ['vk музыка', 'vk music', 'boom'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:mts-premium',
    provider: 'МТС',
    name: 'МТС Premium',
    display_name: 'МТС Premium',
    aliases: ['mts premium', 'мтс премиум', 'мтс premium'],
    icon: 'workspace_premium',
    category_slug: 'entertainment',
    payment_model: 'operator_option',
    plans: [
      {
        id: 'curated:mts-premium:promo',
        name: 'Первый месяц (промо)',
        billing_cycle: 'monthly',
        amount: 99,
        currency: 'RUB',
        amount_type: 'promo',
        price_confidence: 'medium',
        region: ['RU'],
        payment_sources: ['operator'],
        notes: 'Вводная цена для новых подписчиков на первый месяц.',
      },
      {
        id: 'curated:mts-premium:ongoing',
        name: 'Стандартная цена',
        billing_cycle: 'monthly',
        amount: 349,
        currency: 'RUB',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['RU'],
        payment_sources: ['operator'],
        notes: 'Цена после окончания вводного периода — встречается в обзорах, не на официальной тарифной странице.',
      },
    ],
    management_url: 'https://www.mts.ru/premium',
    detection_keywords: ['мтс premium', 'mts premium', 'мтс премиум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена меняется после вводного периода и зависит от тарифа МТС. Проверьте сумму списания в личном кабинете.',
  },
  {
    id: 'curated:sberprime',
    provider: 'Сбер',
    name: 'СберПрайм',
    display_name: 'СберПрайм',
    aliases: ['sberprime', 'сберпрайм', 'sber prime', 'прайм'],
    icon: 'workspace_premium',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:sberprime:base',
        name: 'СберПрайм',
        billing_cycle: 'monthly',
        amount: 399,
        currency: 'RUB',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['RU'],
        notes: 'Цена встречается в обзорах/у агрегаторов; нет уверенности, что это официальная актуальная цена для всех пользователей.',
      },
    ],
    management_url: 'https://www.sberprime.ru',
    detection_keywords: ['сберпрайм', 'sberprime', 'sber prime'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:sberprime-plus',
    provider: 'Сбер',
    name: 'СберПрайм+',
    display_name: 'СберПрайм+',
    aliases: ['sberprime+', 'сберпрайм плюс', 'sber prime plus'],
    icon: 'workspace_premium',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:sberprime-plus:base',
        name: 'СберПрайм+',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
        notes: 'Не удалось уверенно подтвердить актуальную цену расширенного тарифа.',
      },
    ],
    management_url: 'https://www.sberprime.ru',
    detection_keywords: ['сберпрайм+', 'sberprime plus'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:okko',
    provider: 'Okko',
    name: 'Okko',
    display_name: 'Okko',
    aliases: ['окко', 'okko premium', 'okko optimum'],
    icon: 'movie',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:okko:optimum',
        name: 'Optimum',
        billing_cycle: 'monthly',
        amount: 399,
        currency: 'RUB',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['RU'],
        notes: 'Базовый тариф, цена по обзорам/агрегаторам — не проверена напрямую на странице тарифов.',
      },
      {
        id: 'curated:okko:premium',
        name: 'Premium',
        billing_cycle: 'monthly',
        amount: 899,
        currency: 'RUB',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['RU'],
        notes: 'Расширенный тариф с UHD — цена приблизительная.',
      },
    ],
    management_url: 'https://okko.tv',
    detection_keywords: ['okko', 'окко'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'У сервиса несколько тарифов. Цена может отличаться — проверьте сумму списания.',
  },
  {
    id: 'curated:ivi',
    provider: 'Иви',
    name: 'Иви',
    display_name: 'Иви',
    aliases: ['ivi', 'ivi.ru'],
    icon: 'movie',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:ivi:base',
        name: 'Иви Подписка',
        billing_cycle: 'monthly',
        amount: 399,
        currency: 'RUB',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['RU'],
        notes: 'Цена встречается в обзорах — не проверена напрямую на официальном сайте на момент проверки.',
      },
    ],
    management_url: 'https://www.ivi.ru',
    detection_keywords: ['иви', 'ivi'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:wink',
    provider: 'Ростелеком',
    name: 'Wink',
    display_name: 'Wink',
    aliases: ['винк', 'wink ru'],
    icon: 'live_tv',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:wink:base',
        name: 'Wink',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    management_url: 'https://wink.ru',
    detection_keywords: ['wink', 'винк'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от выбранного пакета каналов. Проверьте сумму списания.',
  },
  {
    id: 'curated:telegram-premium',
    provider: 'Telegram',
    name: 'Telegram Premium',
    display_name: 'Telegram Premium',
    aliases: ['телеграм премиум', 'telegram premium', 'тг премиум'],
    icon: 'send',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:telegram-premium:base',
        name: 'Telegram Premium',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'from',
        price_confidence: 'low',
        region: ['RU', 'GLOBAL'],
        payment_sources: ['app_store', 'google_play', 'website'],
        notes: 'Цена сильно различается в зависимости от способа оплаты (App Store/Google Play/сайт/Fragment) — встречаются значения от ~159 до ~650 ₽/мес.',
      },
    ],
    detection_keywords: ['telegram premium', 'телеграм премиум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена сильно зависит от способа оплаты (магазин приложений, сайт, Fragment). Отмена тоже зависит от того, где оформлено.',
  },

  // ──────────────────────────────────────────────────────────────
  // Глобальные сервисы — региональнозависимые цены, не RUB
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:netflix',
    provider: 'Netflix',
    name: 'Netflix',
    display_name: 'Netflix',
    aliases: ['нетфликс', 'netflix'],
    icon: 'movie',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:netflix:standard',
        name: 'Standard',
        billing_cycle: 'monthly',
        amount: 19.99,
        currency: 'USD',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['US', 'GLOBAL'],
        payment_sources: ['website', 'app_store', 'google_play'],
        notes: 'Цена в США как ориентир — фактическая цена зависит от страны аккаунта.',
      },
    ],
    detection_keywords: ['netflix', 'нетфликс'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от региона аккаунта и не указывается в рублях. Проверьте сумму списания.',
  },
  {
    id: 'curated:spotify',
    provider: 'Spotify',
    name: 'Spotify',
    display_name: 'Spotify',
    aliases: ['спотифай', 'spotify premium'],
    icon: 'music_note',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:spotify:premium',
        name: 'Premium Individual',
        billing_cycle: 'monthly',
        amount: 12.99,
        currency: 'USD',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['US', 'GLOBAL'],
        payment_sources: ['website', 'app_store', 'google_play'],
        notes: 'Цена в США как ориентир — фактическая цена зависит от страны аккаунта.',
      },
    ],
    detection_keywords: ['spotify', 'спотифай'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от региона аккаунта и не указывается в рублях. Проверьте сумму списания.',
  },
  {
    id: 'curated:youtube-premium',
    provider: 'Google',
    name: 'YouTube Premium',
    display_name: 'YouTube Premium',
    aliases: ['ютуб премиум', 'youtube premium', 'ютуб'],
    icon: 'smart_display',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:youtube-premium:base',
        name: 'YouTube Premium',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['website', 'app_store', 'google_play'],
      },
    ],
    detection_keywords: ['youtube premium', 'ютуб премиум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от региона аккаунта и не указывается в рублях. Проверьте сумму списания.',
  },
  {
    id: 'curated:apple-music',
    provider: 'Apple',
    name: 'Apple Music',
    display_name: 'Apple Music',
    aliases: ['эпл мюзик', 'apple music'],
    icon: 'music_note',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:apple-music:base',
        name: 'Apple Music',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['app_store'],
      },
    ],
    detection_keywords: ['apple music', 'эпл мюзик'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от региона Apple ID и не указывается в рублях. Проверьте сумму списания.',
  },
  {
    id: 'curated:discord-nitro',
    provider: 'Discord',
    name: 'Discord Nitro',
    display_name: 'Discord Nitro',
    aliases: ['дискорд нитро', 'discord nitro'],
    icon: 'forum',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:discord-nitro:base',
        name: 'Discord Nitro',
        billing_cycle: 'monthly',
        amount: 9.99,
        currency: 'USD',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['US', 'GLOBAL'],
        payment_sources: ['website', 'app_store', 'google_play'],
        notes: 'Цена в США как ориентир — фактическая цена и доступность зависят от региона и способа оплаты.',
      },
    ],
    detection_keywords: ['discord nitro', 'дискорд нитро'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от региона и способа оплаты. Проверьте сумму списания.',
  },
  {
    id: 'curated:google-one',
    provider: 'Google',
    name: 'Google One',
    display_name: 'Google One',
    aliases: ['гугл один', 'google one'],
    icon: 'cloud',
    category_slug: 'utilities',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:google-one:base',
        name: 'Google One',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['website', 'google_play'],
      },
    ],
    detection_keywords: ['google one', 'гугл один'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от объёма хранилища и региона аккаунта. Проверьте сумму списания.',
  },

  // ──────────────────────────────────────────────────────────────
  // iCloud+ — RU тарифы (проверенные, фиксированные)
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:icloud-plus-50gb',
    provider: 'Apple',
    name: 'iCloud+ 50 ГБ',
    display_name: 'iCloud+ 50 ГБ',
    aliases: ['icloud 50gb', 'айклауд 50 гб', 'icloud+ 50gb'],
    icon: 'cloud',
    category_slug: 'utilities',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:icloud-plus-50gb:base',
        name: '50 ГБ',
        billing_cycle: 'monthly',
        amount: 59,
        currency: 'RUB',
        amount_type: 'fixed',
        price_confidence: 'high',
        region: ['RU'],
        payment_sources: ['app_store'],
        notes: 'Цена для региона аккаунта Apple ID = Россия.',
      },
    ],
    pricing_url: 'https://support.apple.com/ru-ru/108047',
    detection_keywords: ['icloud', 'айклауд', 'icloud+'],
    should_autofill_amount: true,
    should_show_in_suggestions: true,
    user_warning: 'Цена верна только для региона аккаунта Apple ID = Россия — для других регионов будет другая сумма.',
    notes: 'Цена подтверждена на официальной странице тарифов Apple для региона RU.',
  },
  {
    id: 'curated:icloud-plus-200gb',
    provider: 'Apple',
    name: 'iCloud+ 200 ГБ',
    display_name: 'iCloud+ 200 ГБ',
    aliases: ['icloud 200gb', 'айклауд 200 гб', 'icloud+ 200gb'],
    icon: 'cloud',
    category_slug: 'utilities',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:icloud-plus-200gb:base',
        name: '200 ГБ',
        billing_cycle: 'monthly',
        amount: 149,
        currency: 'RUB',
        amount_type: 'fixed',
        price_confidence: 'high',
        region: ['RU'],
        payment_sources: ['app_store'],
        notes: 'Цена для региона аккаунта Apple ID = Россия.',
      },
    ],
    pricing_url: 'https://support.apple.com/ru-ru/108047',
    detection_keywords: ['icloud', 'айклауд', 'icloud+'],
    should_autofill_amount: true,
    should_show_in_suggestions: true,
    user_warning: 'Цена верна только для региона аккаунта Apple ID = Россия — для других регионов будет другая сумма.',
    notes: 'Цена подтверждена на официальной странице тарифов Apple для региона RU.',
  },
  {
    id: 'curated:icloud-plus-2tb',
    provider: 'Apple',
    name: 'iCloud+ 2 ТБ',
    display_name: 'iCloud+ 2 ТБ',
    aliases: ['icloud 2tb', 'айклауд 2 тб', 'icloud+ 2tb'],
    icon: 'cloud',
    category_slug: 'utilities',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:icloud-plus-2tb:base',
        name: '2 ТБ',
        billing_cycle: 'monthly',
        amount: 599,
        currency: 'RUB',
        amount_type: 'fixed',
        price_confidence: 'high',
        region: ['RU'],
        payment_sources: ['app_store'],
        notes: 'Цена для региона аккаунта Apple ID = Россия.',
      },
    ],
    pricing_url: 'https://support.apple.com/ru-ru/108047',
    detection_keywords: ['icloud', 'айклауд', 'icloud+'],
    should_autofill_amount: true,
    should_show_in_suggestions: true,
    user_warning: 'Цена верна только для региона аккаунта Apple ID = Россия — для других регионов будет другая сумма.',
    notes: 'Цена подтверждена на официальной странице тарифов Apple для региона RU.',
  },

  // ──────────────────────────────────────────────────────────────
  // AI / продуктивность
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:chatgpt-plus',
    provider: 'OpenAI',
    name: 'ChatGPT Plus',
    display_name: 'ChatGPT Plus',
    aliases: ['чатгпт плюс', 'chat gpt plus', 'gpt plus', 'chatgpt plus'],
    icon: 'smart_toy',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:chatgpt-plus:base',
        name: 'Plus',
        billing_cycle: 'monthly',
        amount: 20,
        currency: 'USD',
        amount_type: 'fixed',
        price_confidence: 'high',
        region: ['US', 'GLOBAL'],
        payment_sources: ['website', 'app_store', 'google_play'],
        notes: 'Официальная цена $20/мес в США/глобально — но для пользователей с RUB-картами фактическое списание зависит от курса, региона и способа оплаты.',
      },
    ],
    pricing_url: 'https://openai.com/chatgpt/pricing/',
    detection_keywords: ['chatgpt plus', 'чатгпт плюс', 'openai'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Официальная цена — $20/мес, но фактическое списание в рублях зависит от курса, региона и способа оплаты. Проверьте сумму списания.',
    notes: 'Цена $20 подтверждена на официальной странице OpenAI — но не подставляется автоматически из-за валютной разницы.',
  },
  {
    id: 'curated:chatgpt-team',
    provider: 'OpenAI',
    name: 'ChatGPT Team',
    display_name: 'ChatGPT Team',
    aliases: ['chatgpt team', 'чатгпт тим'],
    icon: 'smart_toy',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:chatgpt-team:base',
        name: 'Team',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    pricing_url: 'https://openai.com/chatgpt/pricing/',
    detection_keywords: ['chatgpt team'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от количества мест в команде и региона. Проверьте сумму списания.',
  },
  {
    id: 'curated:github-copilot',
    provider: 'GitHub',
    name: 'GitHub Copilot',
    display_name: 'GitHub Copilot',
    aliases: ['гитхаб копайлот', 'github copilot individual'],
    icon: 'code',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:github-copilot:individual',
        name: 'Individual',
        billing_cycle: 'monthly',
        amount: 10,
        currency: 'USD',
        amount_type: 'approximate',
        price_confidence: 'medium',
        region: ['US', 'GLOBAL'],
        payment_sources: ['website'],
        notes: 'Официальная цена в США/глобально — фактическое списание в рублях зависит от курса и способа оплаты.',
      },
    ],
    pricing_url: 'https://github.com/features/copilot/plans',
    detection_keywords: ['github copilot', 'копайлот'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от региона и способа оплаты, не указывается в рублях. Проверьте сумму списания.',
  },
  {
    id: 'curated:adobe-cc',
    provider: 'Adobe',
    name: 'Adobe Creative Cloud',
    display_name: 'Adobe Creative Cloud',
    aliases: ['adobe', 'адоб', 'creative cloud', 'adobe cc'],
    icon: 'palette',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:adobe-cc:base',
        name: 'Creative Cloud',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['website'],
      },
    ],
    detection_keywords: ['adobe', 'creative cloud'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от выбранного плана и региона, официально не продаётся в РФ напрямую. Проверьте сумму списания.',
  },
  {
    id: 'curated:microsoft-365',
    provider: 'Microsoft',
    name: 'Microsoft 365',
    display_name: 'Microsoft 365',
    aliases: ['office 365', 'офис 365', 'microsoft office', 'm365'],
    icon: 'description',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:microsoft-365:base',
        name: 'Microsoft 365 Personal',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['microsoft 365', 'office 365'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена зависит от плана, региона и способа оплаты. Проверьте сумму списания.',
  },
  {
    id: 'curated:figma',
    provider: 'Figma',
    name: 'Figma',
    display_name: 'Figma',
    aliases: ['фигма', 'figma professional'],
    icon: 'design_services',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:figma:professional',
        name: 'Professional',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['figma', 'фигма'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена указана в долларах и зависит от тарифа и способа оплаты. Проверьте сумму списания.',
  },
  {
    id: 'curated:notion',
    provider: 'Notion',
    name: 'Notion',
    display_name: 'Notion',
    aliases: ['ноушен', 'notion plus'],
    icon: 'description',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:notion:plus',
        name: 'Plus',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['notion', 'ноушен'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена указана в долларах и зависит от тарифа и способа оплаты. Проверьте сумму списания.',
  },
  {
    id: 'curated:canva-pro',
    provider: 'Canva',
    name: 'Canva Pro',
    display_name: 'Canva Pro',
    aliases: ['канва про', 'canva pro'],
    icon: 'design_services',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:canva-pro:base',
        name: 'Pro',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['canva', 'канва'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от региона и способа оплаты. Проверьте сумму списания.',
  },

  // ──────────────────────────────────────────────────────────────
  // Группа B — лицензии / разовые покупки (НЕ подписки)
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:logic-pro',
    provider: 'Apple',
    name: 'Logic Pro',
    display_name: 'Logic Pro',
    aliases: ['логик про', 'logic pro x'],
    icon: 'piano',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:logic-pro:license',
        name: 'Покупка лицензии',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['app_store'],
      },
    ],
    detection_keywords: ['logic pro'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка приложения, а не регулярная подписка.',
  },
  {
    id: 'curated:final-cut-pro',
    provider: 'Apple',
    name: 'Final Cut Pro',
    display_name: 'Final Cut Pro',
    aliases: ['финал кат про', 'fcpx'],
    icon: 'movie_edit',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:final-cut-pro:license',
        name: 'Покупка лицензии',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['app_store'],
      },
    ],
    detection_keywords: ['final cut pro'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка приложения, а не регулярная подписка.',
  },
  {
    id: 'curated:davinci-resolve-studio',
    provider: 'Blackmagic Design',
    name: 'DaVinci Resolve Studio',
    display_name: 'DaVinci Resolve Studio',
    aliases: ['давинчи резолв студио', 'resolve studio'],
    icon: 'movie_edit',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:davinci-resolve-studio:license',
        name: 'Покупка лицензии',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['davinci resolve studio'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка лицензии, а не регулярная подписка.',
  },
  {
    id: 'curated:fl-studio',
    provider: 'Image-Line',
    name: 'FL Studio',
    display_name: 'FL Studio',
    aliases: ['фл студио', 'fruity loops'],
    icon: 'piano',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:fl-studio:license',
        name: 'Покупка лицензии',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['fl studio'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка лицензии, а не регулярная подписка.',
  },
  {
    id: 'curated:ableton-live',
    provider: 'Ableton',
    name: 'Ableton Live',
    display_name: 'Ableton Live',
    aliases: ['аблетон лайв', 'ableton'],
    icon: 'piano',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:ableton-live:license',
        name: 'Покупка лицензии',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['ableton live', 'ableton'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка лицензии, а не регулярная подписка.',
  },
  {
    id: 'curated:things-3',
    provider: 'Cultured Code',
    name: 'Things 3',
    display_name: 'Things 3',
    aliases: ['тингс 3', 'things'],
    icon: 'checklist',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:things-3:license',
        name: 'Покупка приложения',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['app_store'],
      },
    ],
    detection_keywords: ['things 3', 'things app'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка приложения, а не регулярная подписка.',
  },
  {
    id: 'curated:affinity-suite',
    provider: 'Serif (Canva)',
    name: 'Affinity',
    display_name: 'Affinity (Photo/Designer/Publisher)',
    aliases: ['аффинити', 'affinity photo', 'affinity designer', 'affinity publisher'],
    icon: 'palette',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:affinity-suite:license',
        name: 'Покупка приложения',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['app_store', 'website'],
      },
    ],
    detection_keywords: ['affinity photo', 'affinity designer', 'affinity publisher'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка приложения, а не регулярная подписка.',
  },
  {
    id: 'curated:camtasia',
    provider: 'TechSmith',
    name: 'Camtasia',
    display_name: 'Camtasia',
    aliases: ['камтазия', 'camtasia studio'],
    icon: 'movie_edit',
    category_slug: 'productivity',
    payment_model: 'license',
    plans: [
      {
        id: 'curated:camtasia:license',
        name: 'Покупка лицензии',
        billing_cycle: 'one_time',
        amount: null,
        currency: null,
        amount_type: 'one_time',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['camtasia'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Это разовая покупка лицензии, а не регулярная подписка.',
  },

  // ──────────────────────────────────────────────────────────────
  // Группа C — бесплатные инструменты (не должны создавать списания)
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:garageband',
    provider: 'Apple',
    name: 'GarageBand',
    display_name: 'GarageBand',
    aliases: ['гараж бэнд', 'garage band'],
    icon: 'piano',
    category_slug: 'productivity',
    payment_model: 'free',
    plans: [
      {
        id: 'curated:garageband:free',
        name: 'Бесплатно',
        billing_cycle: 'unknown',
        amount: 0,
        currency: null,
        amount_type: 'free',
        price_confidence: 'verified',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['garageband'],
    should_autofill_amount: false,
    should_show_in_suggestions: false,
    user_warning: 'Это бесплатное приложение. Добавить его как подписку без расходов?',
  },
  {
    id: 'curated:audacity',
    provider: 'Audacity Team',
    name: 'Audacity',
    display_name: 'Audacity',
    aliases: ['аудасити'],
    icon: 'graphic_eq',
    category_slug: 'productivity',
    payment_model: 'free',
    plans: [
      {
        id: 'curated:audacity:free',
        name: 'Бесплатно',
        billing_cycle: 'unknown',
        amount: 0,
        currency: null,
        amount_type: 'free',
        price_confidence: 'verified',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['audacity'],
    should_autofill_amount: false,
    should_show_in_suggestions: false,
    user_warning: 'Это бесплатное приложение с открытым исходным кодом, а не платная подписка.',
  },
  {
    id: 'curated:obs-studio',
    provider: 'OBS Project',
    name: 'OBS Studio',
    display_name: 'OBS Studio',
    aliases: ['обс студио', 'open broadcaster software'],
    icon: 'videocam',
    category_slug: 'productivity',
    payment_model: 'free',
    plans: [
      {
        id: 'curated:obs-studio:free',
        name: 'Бесплатно',
        billing_cycle: 'unknown',
        amount: 0,
        currency: null,
        amount_type: 'free',
        price_confidence: 'verified',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['obs studio', 'obs'],
    should_autofill_amount: false,
    should_show_in_suggestions: false,
    user_warning: 'Это бесплатное приложение с открытым исходным кодом, а не платная подписка.',
  },
  {
    id: 'curated:khan-academy',
    provider: 'Khan Academy',
    name: 'Khan Academy',
    display_name: 'Khan Academy',
    aliases: ['кан академи', 'khan academy'],
    icon: 'school',
    category_slug: 'education',
    payment_model: 'free',
    plans: [
      {
        id: 'curated:khan-academy:free',
        name: 'Бесплатно',
        billing_cycle: 'unknown',
        amount: 0,
        currency: null,
        amount_type: 'free',
        price_confidence: 'verified',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['khan academy'],
    should_autofill_amount: false,
    should_show_in_suggestions: false,
    user_warning: 'Это бесплатная образовательная платформа, а не платная подписка.',
  },
  {
    id: 'curated:signal',
    provider: 'Signal Foundation',
    name: 'Signal',
    display_name: 'Signal',
    aliases: ['сигнал'],
    icon: 'forum',
    category_slug: 'utilities',
    payment_model: 'free',
    plans: [
      {
        id: 'curated:signal:free',
        name: 'Бесплатно',
        billing_cycle: 'unknown',
        amount: 0,
        currency: null,
        amount_type: 'free',
        price_confidence: 'verified',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['signal messenger'],
    should_autofill_amount: false,
    should_show_in_suggestions: false,
    user_warning: 'Это бесплатный мессенджер, а не платная подписка.',
  },

  // ──────────────────────────────────────────────────────────────
  // Группа D — B2B / низкий приоритет для частных пользователей
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:salesforce',
    provider: 'Salesforce',
    name: 'Salesforce',
    display_name: 'Salesforce',
    aliases: ['сейлсфорс'],
    icon: 'business_center',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:salesforce:base',
        name: 'Salesforce',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['salesforce'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Это корпоративный B2B-сервис — цена сильно зависит от тарифа и числа пользователей.',
  },
  {
    id: 'curated:hubspot',
    provider: 'HubSpot',
    name: 'HubSpot',
    display_name: 'HubSpot',
    aliases: ['хабспот'],
    icon: 'business_center',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:hubspot:base',
        name: 'HubSpot',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['hubspot'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Это корпоративный B2B-сервис — цена сильно зависит от тарифа и числа пользователей.',
  },
  {
    id: 'curated:slack-business',
    provider: 'Slack',
    name: 'Slack',
    display_name: 'Slack (для бизнеса)',
    aliases: ['слак', 'slack business+'],
    icon: 'forum',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:slack-business:base',
        name: 'Slack',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['slack business'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Это корпоративный сервис — цена зависит от тарифа и числа пользователей.',
  },
  {
    id: 'curated:google-workspace',
    provider: 'Google',
    name: 'Google Workspace',
    display_name: 'Google Workspace',
    aliases: ['гугл воркспейс', 'g suite'],
    icon: 'business_center',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:google-workspace:base',
        name: 'Google Workspace',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['google workspace', 'g suite'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Это корпоративный сервис — цена зависит от тарифа и числа пользователей.',
  },
  {
    id: 'curated:zoom-business',
    provider: 'Zoom',
    name: 'Zoom',
    display_name: 'Zoom (для бизнеса)',
    aliases: ['зум', 'zoom pro'],
    icon: 'videocam',
    category_slug: 'productivity',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:zoom-business:base',
        name: 'Zoom',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
      },
    ],
    detection_keywords: ['zoom pro', 'zoom business'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от тарифа, числа пользователей и региона.',
  },

  // ──────────────────────────────────────────────────────────────
  // Группа E — требуют проверки существования регулярного списания
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:vk-messenger',
    provider: 'VK',
    name: 'VK Мессенджер',
    display_name: 'VK Мессенджер',
    aliases: ['вк мессенджер', 'vk messenger'],
    icon: 'forum',
    category_slug: 'utilities',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:vk-messenger:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['vk мессенджер'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса.',
  },
  {
    id: 'curated:mts-music',
    provider: 'МТС',
    name: 'МТС Музыка',
    display_name: 'МТС Музыка',
    aliases: ['мтс музыка', 'mts music'],
    icon: 'music_note',
    category_slug: 'entertainment',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:mts-music:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['мтс музыка'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса.',
  },
  {
    id: 'curated:wildberries-premium',
    provider: 'Wildberries',
    name: 'Wildberries Premium',
    display_name: 'Wildberries Premium',
    aliases: ['вб премиум', 'wb premium', 'вайлдберриз премиум'],
    icon: 'shopping_bag',
    category_slug: 'shopping',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:wildberries-premium:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['wildberries premium', 'wb premium'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса.',
  },
  {
    id: 'curated:ozon-premium',
    provider: 'Ozon',
    name: 'Ozon Premium',
    display_name: 'Ozon Premium',
    aliases: ['озон премиум', 'ozon premium'],
    icon: 'shopping_bag',
    category_slug: 'shopping',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:ozon-premium:base',
        name: 'Ozon Premium',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['ozon premium', 'озон премиум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:ozon-seller',
    provider: 'Ozon',
    name: 'Ozon Seller',
    display_name: 'Ozon Seller (для продавцов)',
    aliases: ['озон селлер', 'ozon продавец'],
    icon: 'storefront',
    category_slug: 'productivity',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:ozon-seller:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['ozon seller'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса.',
  },

  // ──────────────────────────────────────────────────────────────
  // Новые RU mass-market сервисы
  // ──────────────────────────────────────────────────────────────
  {
    id: 'curated:tbank-pro',
    provider: 'Т-Банк',
    name: 'Т-Премиум',
    display_name: 'Т-Премиум',
    aliases: ['t-bank premium', 'тинькофф премиум', 't-премиум', 'тбанк премиум'],
    icon: 'account_balance',
    category_slug: 'finance',
    payment_model: 'bank_fee',
    plans: [
      {
        id: 'curated:tbank-pro:base',
        name: 'Т-Премиум',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
        payment_sources: ['bank'],
      },
    ],
    detection_keywords: ['т-премиум', 't-bank premium', 'тинькофф премиум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена и условия пакета зависят от банка и тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:alfa-premium',
    provider: 'Альфа-Банк',
    name: 'Альфа Premium',
    display_name: 'Альфа Premium',
    aliases: ['альфа премиум', 'alfa premium'],
    icon: 'account_balance',
    category_slug: 'finance',
    payment_model: 'bank_fee',
    plans: [
      {
        id: 'curated:alfa-premium:base',
        name: 'Альфа Premium',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
        payment_sources: ['bank'],
      },
    ],
    detection_keywords: ['альфа premium', 'альфа-банк премиум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена и условия пакета зависят от банка и тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:vtb-privilege',
    provider: 'ВТБ',
    name: 'ВТБ Привилегия',
    display_name: 'ВТБ Привилегия',
    aliases: ['vtb привилегия', 'втб привилегия'],
    icon: 'account_balance',
    category_slug: 'finance',
    payment_model: 'bank_fee',
    plans: [
      {
        id: 'curated:vtb-privilege:base',
        name: 'ВТБ Привилегия',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
        payment_sources: ['bank'],
      },
    ],
    detection_keywords: ['втб привилегия'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    user_warning: 'Цена и условия пакета зависят от банка и тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:yandex-food',
    provider: 'Яндекс',
    name: 'Яндекс Еда',
    display_name: 'Яндекс Еда',
    aliases: ['yandex food', 'яндекс еда плюс'],
    icon: 'restaurant',
    category_slug: 'shopping',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:yandex-food:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['яндекс еда'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса (а не разовые заказы).',
  },
  {
    id: 'curated:kuper',
    provider: 'Купер',
    name: 'Купер',
    display_name: 'Купер',
    aliases: ['kuper', 'сбермаркет'],
    icon: 'shopping_cart',
    category_slug: 'shopping',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:kuper:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['купер', 'kuper', 'сбермаркет'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса (а не разовые заказы).',
  },
  {
    id: 'curated:fitstars',
    provider: 'FitStars',
    name: 'FitStars',
    display_name: 'FitStars',
    aliases: ['фитстарс'],
    icon: 'fitness_center',
    category_slug: 'health',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:fitstars:base',
        name: 'FitStars',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['fitstars', 'фитстарс'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:world-class',
    provider: 'World Class',
    name: 'World Class',
    display_name: 'World Class',
    aliases: ['ворлд класс', 'world class fitness'],
    icon: 'fitness_center',
    category_slug: 'health',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:world-class:base',
        name: 'World Class',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['world class'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от клуба и тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:sber-health',
    provider: 'Сбер',
    name: 'СберЗдоровье',
    display_name: 'СберЗдоровье',
    aliases: ['sber health', 'сбер здоровье'],
    icon: 'health_and_safety',
    category_slug: 'health',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:sber-health:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['сберздоровье', 'sber health'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Проверьте, существует ли регулярная подписка для этого сервиса.',
  },
  {
    id: 'curated:uchi-ru',
    provider: 'Учи.ру',
    name: 'Учи.ру',
    display_name: 'Учи.ру',
    aliases: ['uchi.ru', 'учи ру'],
    icon: 'school',
    category_slug: 'education',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:uchi-ru:base',
        name: 'Учи.ру',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['учи.ру', 'uchi.ru'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от выбранного курса/тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:skyeng',
    provider: 'Skyeng',
    name: 'Skyeng',
    display_name: 'Skyeng',
    aliases: ['скайенг'],
    icon: 'school',
    category_slug: 'education',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:skyeng:base',
        name: 'Skyeng',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['skyeng', 'скайенг'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от выбранного курса и пакета занятий. Проверьте сумму списания.',
  },
  {
    id: 'curated:skillbox',
    provider: 'Skillbox',
    name: 'Skillbox',
    display_name: 'Skillbox',
    aliases: ['скиллбокс'],
    icon: 'school',
    category_slug: 'education',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:skillbox:base',
        name: 'Skillbox',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['skillbox', 'скиллбокс'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от выбранного курса и условий рассрочки. Проверьте сумму списания.',
  },
  {
    id: 'curated:yandex-praktikum',
    provider: 'Яндекс',
    name: 'Яндекс Практикум',
    display_name: 'Яндекс Практикум',
    aliases: ['yandex praktikum', 'яндекс практикум'],
    icon: 'school',
    category_slug: 'education',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:yandex-praktikum:base',
        name: 'Яндекс Практикум',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['яндекс практикум'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от выбранного курса и условий рассрочки. Проверьте сумму списания.',
  },
  {
    id: 'curated:ps-plus',
    provider: 'Sony',
    name: 'PlayStation Plus',
    display_name: 'PlayStation Plus',
    aliases: ['пс плюс', 'ps plus', 'playstation plus'],
    icon: 'sports_esports',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:ps-plus:base',
        name: 'PlayStation Plus',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['website'],
      },
    ],
    detection_keywords: ['playstation plus', 'ps plus'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от региона аккаунта PSN и выбранного тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:xbox-game-pass',
    provider: 'Microsoft',
    name: 'Xbox Game Pass',
    display_name: 'Xbox Game Pass',
    aliases: ['икс бокс гейм пасс', 'game pass', 'xbox game pass'],
    icon: 'sports_esports',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:xbox-game-pass:base',
        name: 'Xbox Game Pass',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['GLOBAL'],
        payment_sources: ['website'],
      },
    ],
    detection_keywords: ['xbox game pass', 'game pass'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена зависит от региона аккаунта и выбранного тарифа. Проверьте сумму списания.',
  },
  {
    id: 'curated:vk-play',
    provider: 'VK',
    name: 'VK Play',
    display_name: 'VK Play',
    aliases: ['вк плей', 'vkplay'],
    icon: 'sports_esports',
    category_slug: 'entertainment',
    payment_model: 'subscription',
    plans: [
      {
        id: 'curated:vk-play:base',
        name: 'VK Play',
        billing_cycle: 'monthly',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['vk play', 'вк плей'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Цена может отличаться. Проверьте сумму списания.',
  },
  {
    id: 'curated:boosty',
    provider: 'Boosty',
    name: 'Boosty',
    display_name: 'Boosty (донат/подписка на автора)',
    aliases: ['бусти', 'boosty подписка'],
    icon: 'volunteer_activism',
    category_slug: 'entertainment',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:boosty:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['boosty', 'бусти'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Сумма зависит от того, на какого автора и какой уровень подписки вы оформили. Проверьте сумму списания.',
  },
  {
    id: 'curated:donationalerts',
    provider: 'DonationAlerts',
    name: 'DonationAlerts',
    display_name: 'DonationAlerts (донат/подписка)',
    aliases: ['донейшн алертс', 'donation alerts'],
    icon: 'volunteer_activism',
    category_slug: 'entertainment',
    payment_model: 'unknown',
    plans: [
      {
        id: 'curated:donationalerts:unknown',
        name: 'Неизвестно',
        billing_cycle: 'unknown',
        amount: null,
        currency: null,
        amount_type: 'unknown',
        price_confidence: 'unknown',
        region: ['RU'],
      },
    ],
    detection_keywords: ['donationalerts'],
    should_autofill_amount: false,
    should_show_in_suggestions: true,
    is_low_priority: true,
    user_warning: 'Сумма зависит от того, кому и в каком размере вы оформили донат/подписку. Проверьте сумму списания.',
  },
]
